# Reddit → Lemmy Bridge (Example Compose File)
# Compatible with Python 3.12 and Lemmy-Ansible setups
# 
# This example is safe to publish in GitHub and shows sane defaults
# for local or containerized deployments.

services:
  reddit-lemmy-bridge:
    container_name: reddit-lemmy-bridge
    build: .
    restart: unless-stopped
    env_file:
      - .env
    working_dir: /app
    volumes:
      # Mirror main bridge script (read-only for safety)
      - ./auto_mirror.py:/app/auto_mirror.py:ro
      # Persistent data: tokens, SQLite cache, maps
      - ./data:/app/data
    environment:
      - DATA_DIR=/app/data
      - PYTHONUNBUFFERED=1
    command: ["python3", "-u", "auto_mirror.py"]
    networks:
      - lemmy_net
    hostname: reddit-lemmy-bridge
    user: "1000:1000"

  reddit-comment-mirror:
    container_name: reddit-comment-mirror
    build: .
    restart: unless-stopped
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./comment_mirror.py:/app/comment_mirror.py:ro
      - ./data:/app/data
    environment:
      - DATA_DIR=/app/data
      - PYTHONUNBUFFERED=1
    # Example: separate Lemmy account for comment posting
    command: >
      bash -c "
        export LEMMY_USER=$${LEMMY_USER_COMMENTS} &&
        export LEMMY_PASS=$${LEMMY_PASS_COMMENTS} &&
        python3 -u comment_mirror.py
      "
    networks:
      - lemmy_net
    hostname: reddit-comment-mirror
    user: "1000:1000"

  reddit-edit-sync:
    container_name: reddit-edit-sync
    build: .
    restart: unless-stopped
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./edit_sync.py:/app/edit_sync.py:ro
      - ./data:/app/data
    environment:
      - DATA_DIR=/app/data
      - PYTHONUNBUFFERED=1
    command: ["python3", "-u", "edit_sync.py"]
    networks:
      - lemmy_net
    hostname: reddit-edit-sync
    user: "1000:1000"

# External Lemmy network
networks:
  lemmy_net:
    external: true
    # Replace with your Lemmy-Ansible network name (check with `docker network ls | grep lemmy`)
    name: fosscadguncaddesignscom_default
